"""workout intensity to string

Revision ID: 03495d7d344c
Revises: 2afdfbfb1fd6
Create Date: 2026-08-19 10:59:21.616714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03495d7d344c'
down_revision: Union[str, None] = '2afdfbfb1fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('weight-logs')
    # 安全加列：workout_logs 已有数据行，直接 NOT NULL 会因无值报错。
    # 1) 先以可空方式加列；2) 回填默认值；3) 再改成不可空。
    op.add_column('workout_logs', sa.Column('duration_min', sa.Integer(), nullable=True))
    op.execute("UPDATE workout_logs SET duration_min = 0 WHERE duration_min IS NULL")
    op.alter_column('workout_logs', 'duration_min', nullable=False)
    op.alter_column('workout_logs', 'intensity',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('workout_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workout_logs', 'duration_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('duration_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('workout_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_logs', 'intensity',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=False)
    # 与 upgrade 对称：先改回可空，再删除列
    op.alter_column('workout_logs', 'duration_min', nullable=True)
    op.drop_column('workout_logs', 'duration_min')
    op.create_table('weight-logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('waist_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='weight-logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weight-logs_pkey')
    )
    op.drop_table('weight_logs')
    # ### end Alembic commands ###
