"""add profiles table

Revision ID: bbb4906c9adf
Revises: 7f3602f8287e
Create Date: 2026-08-13 10:02:26.691460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb4906c9adf'
down_revision: Union[str, None] = '7f3602f8287e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('current_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=10), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('diet_preference', sa.String(length=255), nullable=True),
    sa.Column('health_notes', sa.String(length=255), nullable=True),
    sa.Column('goal_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
